name: Run Template Test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      configuration:
        required: true
        type: string
        default: Release

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: "Add NuGet Source"
        run: dotnet nuget add source "https://nuget.pkg.github.com/WolfBublitz/index.json" --username WolfBublitz --password ${GITHUB_TOKEN} --store-password-in-clear-text --name github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: dotnet restore
      - name: Install Template
        run: dotnet new install src/bin/Release/WB.TestTemplate*.nupkg --force
      - name: Instantiate Test Project from Template
        run: dotnet new wbtest --output TestProject
      - name: Run Test Project
        run: cd TestProject/src && dotnet test --configuration ${{ inputs.configuration }}
